# Generated by Django 4.0.1 on 2022-03-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='url_img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='imgProfile/'),
        ),
    ]
